// Category-first ingredient data — each word appears in exactly one category
const CATEGORIES: Record<string, string[]> = {
  produce: [
    // vegetables
    "artichoke", "arugula", "asparagus", "beet", "bell", "bok", "broccoli",
    "broccolini", "brussel", "cabbage", "carrot", "cauliflower", "celery",
    "cilantro", "chard", "collard", "corn", "cucumber", "daikon", "eggplant",
    "endive", "fennel", "garlic", "kale", "kohlrabi", "leek", "lettuce",
    "okra", "onion", "parsnip", "pea", "potato", "pumpkin", "radicchio",
    "radish", "rhubarb", "rutabaga", "shallot", "spinach", "squash",
    "tomatillo", "tomato", "scallion", "turnip", "watercress", "yam",
    "zucchini", "chayote", "chives", "kabocha", "taro", "bean", "greens",
    "dandelion", "mâche", "mizuna", "purslane", "tatsoi", "burdock",
    "celeriac", "jicama", "sunchoke", "malanga", "salsify", "scorzonera",
    "cactus", "fern", "ginger", "horseradish", "mushroom", "sorrel",
    "pepper", "jalapeño", "habanero", "serrano", "poblano",
    // fruits
    "apple", "apricot", "avocado", "banana", "blackberry", "blueberry",
    "boysenberry", "cantaloupe", "cherry", "clementine", "coconut",
    "cranberry", "currant", "dragonfruit", "durian", "elderberry", "fig",
    "gooseberry", "date", "grape", "grapefruit", "guava", "honeydew",
    "huckleberry", "jackfruit", "kiwi", "kumquat", "lemon", "lime",
    "lychee", "mandarin", "mango", "mulberry", "nectarine", "orange",
    "papaya", "passionfruit", "peach", "pear", "persimmon", "pineapple",
    "plum", "pomegranate", "pomelo", "quince", "raspberry", "redcurrant",
    "starfruit", "strawberry", "tangerine", "melon", "plantain",
    "acerola", "ackee", "açaí", "aronia", "babaco", "bilberry", "breadfruit",
    "blackcurrant", "calamondin", "cherimoya", "cloudberry", "damson",
    "feijoa", "guavaberry", "jostaberry", "langsat", "loquat", "mangosteen",
    "marionberry", "medlar", "noni", "pawpaw", "physalis", "rambutan",
    "salak", "soursop", "tamarillo", "tamarind", "sapote",
  ],
  fish: [
    "anchovy", "anchovies", "bass", "catfish", "cod", "flounder", "grouper",
    "haddock", "halibut", "herring", "mackerel", "mahi", "marlin",
    "monkfish", "perch", "pollock", "salmon", "sardine", "snapper",
    "swordfish", "tilapia", "trout", "tuna", "wahoo", "whiting",
    "albacore", "char", "shrimp", "barracuda", "bluefish", "butterfish",
    "carp", "caviar", "cobia", "escolar", "hake", "kingfish", "roughy",
    "pompano", "rockfish", "sablefish", "shark", "sturgeon", "tilefish",
    "turbot", "whitefish", "yellowfin", "bigeye", "skipjack", "yellowtail",
    "bluefin", "chub", "dogfish", "dorado", "eel", "mullet", "grenadier",
    "shad", "dory", "sole", "lingcod", "mahi-mahi", "milkfish", "pike",
    "opah", "paddlefish", "parrotfish", "sockeye", "steelhead", "tripletail",
    "walleye", "weakfish", "crab", "lobster", "clam", "mussel", "oyster",
    "scallop", "squid", "octopus", "crawfish", "prawn",
  ],
  meat: [
    "beef", "chicken", "pork", "lamb", "turkey", "duck", "goose", "venison",
    "bison", "veal", "goat", "rabbit", "ostrich", "quail", "pheasant",
    "fowl", "elk", "boar", "mutton", "squab", "hare", "emu", "yak", "moose",
    "caribou", "antelope", "liver", "kidney", "sweetbreads", "tripe",
    "heart", "tongue", "sausage", "bacon", "ham", "salami", "pepperoni",
    "pancetta", "prosciutto", "pastrami", "steak", "brisket", "ribs",
  ],
  dairy: [
    "milk", "cream", "butter", "cheese", "yogurt", "kefir", "ghee",
    "buttermilk", "curd", "gelato", "ricotta", "mascarpone", "brie",
    "camembert", "cheddar", "gouda", "mozzarella", "provolone", "parmesan",
    "feta", "egg", "pecorino", "romano", "asiago", "stilton", "roquefort",
    "gruyere", "emmental", "halloumi", "paneer", "queso", "manchego",
    "taleggio", "gorgonzola", "havarti", "munster", "burrata", "edam",
    "neufchatel", "colby", "babybel", "whey", "cottage",
  ],
  condiments: [
    "ketchup", "mustard", "mayo", "mayonnaise", "relish", "worcestershire",
    "barbecue", "ranch", "salsa", "pickle", "tahini", "capers",
  ],
  spice: [
    "allspice", "anise", "asafoetida", "basil", "bay", "caraway",
    "cardamom", "cayenne", "chili", "cinnamon", "cloves", "coriander",
    "cumin", "curry", "dill", "fenugreek", "harissa", "provence", "juniper",
    "lavender", "lemongrass", "mace", "marjoram", "mint", "nutmeg",
    "oregano", "paprika", "parsley", "rosemary", "saffron", "sage",
    "savory", "sumac", "tarragon", "thyme", "turmeric", "vanilla", "zaatar",
    "masala", "garam", "salt", "seasoning",
  ],
  baking: [
    "flour", "oil", "honey", "yeast", "starch", "sugar", "cornstarch",
    "cocoa", "chocolate", "maple", "syrup", "molasses", "extract",
    "shortening", "cornmeal", "oat", "oats",
  ],
  "beans & rice": [
    "rice", "lentil", "chickpea", "quinoa", "farro", "barley", "couscous",
  ],
  asian: [
    "gochujang", "soy", "mirin", "sambal", "miso", "hoisin", "tamari",
    "sriracha", "doenjang", "ssamjang", "wasabi", "furikake", "nori",
    "wakame", "bonito", "dashi", "kombu", "udon", "soba", "ramen",
    "wonton", "dumpling", "mochi", "pocky", "matcha", "lotus", "pandan",
    "bamboo", "galangal", "tempeh", "seitan", "mung", "adzuki", "cheong",
    "teriyaki", "ponzu", "yuzu", "kewpie", "tofu", "kimchi", "seaweed",
    "noodle",
  ],
  pasta: [
    "spaghetti", "penne", "fusilli", "farfalle", "linguine", "rigatoni",
    "macaroni", "fettuccine", "orzo", "pappardelle", "tagliatelle",
    "gnocchi", "lasagna", "tortellini", "ravioli", "ziti", "conchiglie",
    "cavatappi", "orecchiette", "ditalini", "bucatini", "cannelloni",
    "manicotti", "capellini", "gemelli", "rotini", "pasta",
  ],
  liquor: [
    "beer", "wine", "whiskey", "vermouth", "bourbon", "campari", "vodka",
    "rum", "gin", "tequila", "brandy", "sake", "champagne",
  ],
};

// Compound phrases — checked before single-word lookup
const COMPOUND_PHRASES: [string, string][] = [
  ["olive oil", "baking"],
  ["coconut oil", "baking"],
  ["vegetable oil", "baking"],
  ["canola oil", "baking"],
  ["sesame oil", "asian"],
  ["fish sauce", "asian"],
  ["soy sauce", "asian"],
  ["oyster sauce", "asian"],
  ["hoisin sauce", "asian"],
  ["rice vinegar", "asian"],
  ["rice wine", "asian"],
  ["cream cheese", "dairy"],
  ["sour cream", "dairy"],
  ["ice cream", "dairy"],
  ["heavy cream", "dairy"],
  ["whipping cream", "dairy"],
  ["ground ginger", "spice"],
  ["ground pepper", "spice"],
  ["fennel seed", "spice"],
  ["celery seed", "spice"],
  ["red pepper", "spice"],
  ["chili powder", "spice"],
  ["chili flakes", "spice"],
  ["garlic powder", "spice"],
  ["onion powder", "spice"],
  ["black bean", "beans & rice"],
  ["pinto bean", "beans & rice"],
  ["kidney bean", "beans & rice"],
  ["navy bean", "beans & rice"],
  ["lima bean", "beans & rice"],
  ["cannellini bean", "beans & rice"],
  ["white bean", "beans & rice"],
  ["great northern", "beans & rice"],
  ["hot sauce", "condiments"],
  ["baking soda", "baking"],
  ["baking powder", "baking"],
  ["brown sugar", "baking"],
  ["powdered sugar", "baking"],
  ["confectioner sugar", "baking"],
  ["maple syrup", "baking"],
  ["corn syrup", "baking"],
  ["tomato paste", "produce"],
  ["tomato sauce", "produce"],
];

// Built at module load — flat map from keyword -> location
const ingredientMap: Map<string, string> = new Map();
for (const [category, words] of Object.entries(CATEGORIES)) {
  for (const word of words) {
    ingredientMap.set(word, category);
  }
}

export { ingredientMap, COMPOUND_PHRASES };

export const STORE_LOCATIONS = [
  "produce",
  "fish",
  "meat",
  "dairy",
  "condiments",
  "spice",
  "baking",
  "beans & rice",
  "asian",
  "pasta",
  "liquor",
  "other",
];
